[tool.poetry]
name = "versioning-util"
version = "0.1.0"
description = ""
authors = ["imnublet <sayfgmaul@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
importlib-resources = "^6.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
